spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: ****************************
      secret-key: ******************************
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: agribusiness
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: *******************************
        templateId: *******************************
        appcode: *******************************
  application:
    name: agribusiness-third-party
server:
  port: 30000

