#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: www.qq.com
#          predicates:
#            - Query=url,qq